export {
  HUNT_AUTO_ROUTER_LABEL as V1_MINI_AUTO_ROUTER_LABEL,
  HUNT_DEFAULT_MINI_MODEL_DISPLAY_NAME as V1_MINI_MODEL_DISPLAY_NAME,
  HUNT_DEFAULT_MODEL_ROUTE_ID as V1_MINI_DEFAULT_MODEL_ROUTE_ID,
  HUNT_MODEL_ROUTE_OPTIONS as V1_MINI_MODEL_ROUTE_OPTIONS,
  resolveHuntModelRoute as resolveV1MiniModelRoute,
} from "@/lib/simplify/engines/hunt-route"
